Don't save dupe entries in Extra Folders to prevent performance degra…
TurBoss/7h pull request #53
Opened 2019-11-16 02:53 UTC by unab0mb

…dation, fix dupe direct/music folders on 1st run, ensure direct/music always in configuration per EQ2Alyza's guide.

2019-11-16 09:50 UTC, julianxhokaxhiu commented on 7thWorkshop/fSettings.cs
> +            if (!ExtraFoldersList.Contains("direct", StringComparer.OrdinalIgnoreCase)) ExtraFoldersList.Add("direct");
Please use `InvariantCultureIgnoreCase`

2019-11-16 09:50 UTC, julianxhokaxhiu commented on 7thWorkshop/fSettings.cs
> +            if (!ExtraFoldersList.Contains("music")) ExtraFoldersList.Add("music");
Here it is missing, please add the `StringComparer.InvariantCultureIgnoreCase` as well

2019-11-16 09:50 UTC, julianxhokaxhiu commented on 7thWorkshop/fSettings.cs
> +            Sys.Settings.ExtraFolders = ExtraFoldersList.Distinct(StringComparer.OrdinalIgnoreCase).ToList();
Same here, please use `InvariantCultureIgnoreCase`

2019-11-16 09:51 UTC, julianxhokaxhiu commented on 7thHeaven.Code/Sys.cs
> +            //if (Settings.ExtraFolders == null || Settings.ExtraFolders.Count == 0) Settings.ExtraFolders = new List<string>() { "direct", "music" };
Just delete both lines, if we need this code we can get it back from git

2019-11-16 09:52 UTC, julianxhokaxhiu requested changes
Overall the PR looks good but there are minor fixes required. Let me know when they are done by requesting another review.

2019-11-16 16:14 UTC, julianxhokaxhiu approved these changes
LGTM

2019-11-18 14:00 UTC, merged

2019-11-18 14:00 UTC, TurBoss commented
just tested and works fine

Thank you!